ready_sound: sounds/beep.wav
debug: true
debounce_seconds: 0.25
aplay_card: 
streamdeck:
  enabled: false
  only_15_key: true
  brightness: 45
  # Optional button images. Keys can be STREAMDECK_1..STREAMDECK_15 or 1..15.
  images:
    STREAMDECK_1: keys/streamdeck_key.png
  #   2: images/button2.png
bindings:
  STREAMDECK_1: sounds/beep.wav
  STREAMDECK_2: sounds/beep.wav
  STREAMDECK_3: sounds/beep.wav
  KEY_PAGEDOWN: sounds/beep.wav
  KEY_PAGEUP: sounds/beep.wav
  KEY_DOT: sounds/beep.wav
