ready_sound: /home/bbplayers/sfxbox/sounds/ready.wav
debug: true
debounce_seconds: 0.25
sounds:
  default: /home/bbplayers/sfxbox/sounds/default.wav
  space: /home/bbplayers/sfxbox/sounds/space.wav
  enter: /home/bbplayers/sfxbox/sounds/enter.wav
